### ISSUE TITLE
Question about extra channels in TIFF

### ISSUE THREAD

**Issue by diuming** [Mrwerdo/LibTIFF#1]
I have a tiff image with 7 channels(CMYK + 3 spot channels).
What's the correct way to deal with `TIFFTAG_EXTRASAMPLES`? (count? types?)

Does this package can deal with extra channels, like photoshop?

![CMYK+3Spot-3](https://user-images.githubusercontent.com/39903550/129648172-f1744056-c381-4e8f-b08b-d35f71d0c306.png)

**Comment by mrwerdo** [comment]
Hi Mate,

I'm haven't tested reading a tiff file with 7 channels 🙂. At the time I was writing it for generating drafts which was oh so long ago. It might work if you read the image with the a suitably sized channel:

```swift
var image = try TIFFImage<UInt32>(readingAt: "img.tiff")

let y = 5
let x = 5
let c = 6

let w = image.size.width
let spp = image.attributes.samplesPerPixel

// Get the 7th component at coordinates (5, 5).
image.buffer[(w * y + x) * spp + c]
```

If you want to check the type of extra samples then you can consult `image.attributes.extraSamples`. It's probably all zeros because they are not [alpha channels](https://www.awaresystems.be/imaging/tiff/tifftags/extrasamples.html)

Finally, if you find something that doesn't work and want to contribute a patch or other improvement then I'd be happy to accept.
